server:
  port: ${PORT:0}    
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}  
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: microservices-users
      
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_microservices_users
    username: postgres
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
logging:
  level:
    org:
      hibernate:
        type: debug        